### ISSUE TITLE
nvme 認識しない

### ISSUE THREAD

**Issue by toshi-mtk** [qbilinux/qbilinux#13]
カーネルが nvme なディスクを認識しない．
インストーラーもインストールされるカーネルも．

**Comment by t-matsuki** [comment]
とりあえず認識するようにした．

**Comment by toshi-mtk** [comment]
インストールは可能だけど、grub のインストールに失敗するみたい。

**Comment by toshi-mtk** [comment]
0.4 で一応インストールできるように調整済みなのでクローズ。
